src/main/java/com/campper/global/common/error/ErrorCode.java, src/main/java/com/campper/global/common/error/GlobalExceptionHandler.java, src/main/java/com/campper/global/common/error/exception/BadRequestException.java, src/main/java/com/campper/global/common/error/exception/BaseException.java, src/main/java/com/campper/global/common/error/exception/ForbiddenException.java, src/main/java/com/campper/global/common/error/exception/InternalServerException.java, src/main/java/com/campper/global/common/error/exception/NotFoundException.java, src/main/java/com/campper/global/common/error/exception/UnauthorizedException.java, src/main/java/com/campper/global/common/response/CommonResponse.java, src/main/java/com/campper/global/common/response/ErrorResponse.java, src/main/java/com/campper/global/common/response/SuccessResponse.java
---
리스폰스 관련 세팅 
---
set/response
---
이슈 번호
- close #
---
특이사항
=> :rocket: 리스폰스 관련 세팅 완료

src/main/java/com/campper/domain/boards/mapper/BoardMapper.java, src/main/java/com/campper/domain/camps/mapper/CampMapper.java, src/main/java/com/campper/domain/comments/mapper/CommentMapper.java, src/main/java/com/campper/domain/users/mapper/UserMapper.java, src/main/java/com/campper/domain/votes/mapper/VoteMapper.java, src/main/java/com/campper/global/config/SecurityConfig.java, src/main/resources/application.yml, src/main/resources/mapper/board.xml, src/main/resources/mapper/camp.xml, src/main/resources/mapper/comment.xml, src/main/resources/mapper/user.xml, src/main/resources/mapper/vote.xml
mybatis 기본 구조 세팅 작업 진행
---
mybatis를 사용하기 위한 기본 구조 세팅을 했습니다.
아직 인증 작업을 처리하지 않았기에 모든 url에 대해 접근이 가능하도록 허용했습니다.
---
set/mapper
---
---
=> :rocket: set(mybatis): mybatis 기본 세팅 

src/main/java/com/campper/domain/comments/repository/CommentRepository.java, src/main/java/com/campper/domain/users/entity/Role.java, src/main/java/com/campper/domain/users/service/UserServiceImpl.java, src/main/java/com/campper/global/security/CustomUserDetailServiceImpl.java
---
인증 버그 해결
---
bug/auth
---
이슈 번호
- ❌ 
---
❌
=> :rocket: bug(auth): 인증 버그 해결

src/main/java/com/campper/domain/boards/BoardController.java, src/main/java/com/campper/domain/boards/dto/request/BoardParameterDto.java, src/main/java/com/campper/domain/boards/dto/response/GetBoardDetailDto.java, src/main/java/com/campper/domain/boards/dto/response/GetBoardDto.java, src/main/java/com/campper/domain/boards/entity/Board.java, src/main/java/com/campper/domain/boards/repository/BoardRepository.java, src/main/java/com/campper/domain/boards/service/BoardService.java, src/main/java/com/campper/domain/boards/service/BoardServiceImpl.java, src/main/java/com/campper/domain/users/entity/User.java, src/main/java/com/campper/domain/users/repository/UserRepository.java, src/main/java/com/campper/global/common/error/ErrorCode.java, src/main/java/com/campper/global/common/util/PageNavigation.java, src/main/resources/mapper/board.xml, src/main/resources/mapper/user.xml
---
- Board 페이징 서비스
- Board, User id 유효성 검사
---
feat/board-service
---
이슈 번호
- ❌ 
---
❌
=> 🚀board 페이징 기능

src/main/java/com/campper/domain/boards/repository/BoardRepository.java, src/main/java/com/campper/domain/like/boards/BoardLikeController.java, src/main/java/com/campper/domain/like/boards/entity/BoardLike.java, src/main/java/com/campper/domain/like/boards/repository/BoardLikeRepository.java, src/main/java/com/campper/domain/like/boards/service/BoardLikeService.java, src/main/java/com/campper/domain/like/boards/service/BoardLikeServiceImpl.java, src/main/resources/mapper/board.xml, src/main/resources/mapper/boardLike.xml
---
게시글 좋아요 기능 추가
---
feat/board-like
---
❌ 
---
❌
=> :rocket: board like

src/main/java/com/campper/domain/comments/repository/CommentRepository.java, src/main/java/com/campper/domain/like/comments/CommentLikeController.java, src/main/java/com/campper/domain/like/comments/entity/CommentLike.java, src/main/java/com/campper/domain/like/comments/repository/CommentLikeRepository.java, src/main/java/com/campper/domain/like/comments/service/CommentLikeService.java, src/main/java/com/campper/domain/like/comments/service/CommentLikeServiceImpl.java, src/main/resources/mapper/comment.xml, src/main/resources/mapper/commentLike.xml
---
댓글 좋아요 기능
---
feat/comment-like
---
이슈 번호
- ❌ 
---
❌
=> :rocket: comment 좋아요 기능

src/main/java/com/campper/domain/camps/repository/CampRepository.java, src/main/java/com/campper/domain/camps/service/CampServiceImpl.java, src/main/java/com/campper/domain/like/boards/entity/BoardLike.java, src/main/java/com/campper/domain/like/camps/CampDibsController.java, src/main/java/com/campper/domain/like/camps/entity/CampDibs.java, src/main/java/com/campper/domain/like/camps/repository/CampDibsRepository.java, src/main/java/com/campper/domain/like/camps/service/CampDibsService.java, src/main/java/com/campper/domain/like/camps/service/CampDibsServiceImpl.java, src/main/resources/mapper/camp.xml, src/main/resources/mapper/campdibs.xml
---
캠프 찜 구현
---
feat/camp-dibs
---
이슈 번호
- ❌ 
---
❌
=> :rocket: camp dibs

src/main/java/com/campper/domain/boards/dto/request/SaveBoardDto.java, src/main/java/com/campper/domain/boards/entity/Category.java, src/main/java/com/campper/domain/comments/CommentController.java, src/main/java/com/campper/domain/comments/dto/request/CommentParameterDto.java, src/main/java/com/campper/domain/comments/dto/request/SaveCommentDto.java, src/main/java/com/campper/domain/comments/service/CommentService.java, src/main/java/com/campper/domain/comments/service/CommentServiceImpl.java
---
- 게시글 카테고리에 ENUM 유효성 검사 추가
- 댓글 api에 boardId 보이도록 수정
---
feat/category-enum-valid
---
이슈 번호
- #20 
---
❌
=> :hammer: category enum valid

src/main/java/com/campper/domain/camps/CampController.java, src/main/java/com/campper/domain/camps/dto/CampDto.java, src/main/java/com/campper/domain/camps/dto/VoteCampDto.java, src/main/java/com/campper/domain/like/camps/CampDibsController.java, src/main/java/com/campper/domain/votes/VoteController.java, src/main/java/com/campper/domain/votes/dto/response/GetVoteDto.java, src/main/java/com/campper/global/config/SwaggerConfig.java
---
컨트롤러 API모델 추가
---
refac/controller
---
---
특이사항
=> :hammer: 컨트롤러 API모델 추가

src/main/java/com/campper/domain/auth/AuthController.java, src/main/java/com/campper/domain/boards/BoardController.java, src/main/java/com/campper/domain/boards/dto/response/GetBoardDto.java, src/main/java/com/campper/domain/users/UserController.java
---
board response에 좋아요 수 추가
---
feat/board-response-dto
---
이슈 번호
- ❌ 
---
❌
=> :rocket: board response 수정

src/main/java/com/campper/domain/boards/BoardController.java, src/main/java/com/campper/domain/boards/dto/response/GetBoardDetailDto.java, src/main/java/com/campper/domain/boards/service/BoardServiceImpl.java, src/main/java/com/campper/domain/comments/CommentController.java, src/main/java/com/campper/domain/comments/dto/request/SaveCommentDto.java, src/main/java/com/campper/domain/comments/dto/response/GetCommentDto.java, src/main/java/com/campper/domain/comments/entity/Comment.java, src/main/java/com/campper/domain/comments/service/CommentServiceImpl.java, src/main/java/com/campper/domain/like/boards/service/BoardLikeServiceImpl.java, src/main/java/com/campper/domain/users/dto/response/GetUserProfileDto.java
---
게시글 response dto 수정
댓글 response dto 수정
---
feat/board-response-dto
---
이슈 번호
- ❌ 
---
❌
=> :rocket: Feat response dto

src/main/java/com/campper/domain/camps/dto/response/GetCampDto.java
---
작업 사항
---
작업 브랜치
---
이슈 번호
- close #
---
특이사항
=> :rocket: refac(camp): JSON 변경

src/main/java/com/campper/domain/comments/CommentController.java, src/main/java/com/campper/domain/comments/dto/request/SaveCommentDto.java, src/main/java/com/campper/domain/comments/service/CommentService.java, src/main/java/com/campper/domain/comments/service/CommentServiceImpl.java
---
comment param 수정
save dto에 boardId 추가
---
hotfix/comment
---
이슈 번호
- ❌ 
---
❌
=> :hammer: comment param 수정

src/main/java/com/campper/domain/boards/dto/response/GetBoardDetailDto.java, src/main/java/com/campper/domain/boards/dto/response/GetBoardDto.java, src/main/java/com/campper/domain/boards/entity/Board.java, src/main/java/com/campper/domain/boards/entity/Image.java, src/main/java/com/campper/domain/boards/service/BoardServiceImpl.java, src/main/java/com/campper/domain/comments/dto/response/GetCommentDto.java, src/main/java/com/campper/domain/comments/entity/Comment.java, src/main/java/com/campper/global/common/entity/BaseEntity.java, src/main/java/com/campper/global/common/entity/TimeBaseEntity.java
---
BaseEntity 에 setter 어노테이션 추가
response dto 에 생성일 추가
---
refactor/response-createdAt
---
이슈 번호
- ❌ 
---
❌
=> 🔨 Refactor response 생성일

src/main/java/com/campper/domain/users/dto/response/GetUserProfileDto.java, src/main/resources/mapper/board.xml, src/main/resources/mapper/comment.xml
---
프로필 정보에 authKey추가
게시글에서 isDeleted 된 글 제외
댓글에서 isDeleted 된 글 제외
---
refactor/user-response
---
이슈 번호
- ❌ 
---
❌
=> 🔨 user response

src/main/java/com/campper/domain/votes/VoteController.java
---
작업 사항
---
작업 브랜치
---
이슈 번호
- close #
---
특이사항
=> :rocket: feat(vote): 컨트롤러 변경 !

build.gradle, src/main/java/com/campper/domain/auth/AuthController.java, src/main/java/com/campper/domain/auth/jwt/inmemory/blackList/AccessToken.java, src/main/java/com/campper/domain/auth/jwt/inmemory/blackList/AccessTokenRepository.java, src/main/java/com/campper/domain/auth/jwt/inmemory/reissue/RefreshToken.java, src/main/java/com/campper/domain/auth/jwt/inmemory/reissue/RefreshTokenRepository.java, src/main/java/com/campper/domain/auth/jwt/inmemory/reissue/service/RefreshTokenService.java, src/main/java/com/campper/domain/auth/jwt/inmemory/reissue/service/RefreshTokenServiceImpl.java, src/main/java/com/campper/domain/auth/service/AuthService.java, src/main/java/com/campper/domain/auth/service/AuthServiceImpl.java, src/main/java/com/campper/global/common/error/ErrorCode.java, src/main/java/com/campper/global/common/error/GlobalExceptionHandler.java, src/main/java/com/campper/global/common/error/jwt/JwtAccessDeniedHandler.java, src/main/java/com/campper/global/common/error/jwt/JwtAuthenticationEntryPoint.java, src/main/java/com/campper/global/config/SecurityConfig.java, src/main/java/com/campper/infra/feign/FeignConfig.java, src/main/java/com/campper/infra/feign/camp/client/CampInfoClient.java, src/main/java/com/campper/infra/redis/RedisConfig.java, src/main/resources/application.yml
---
작업 사항
---
feat/auth
---
이슈 번호
- close #36 
- close #37 
---
특이사항
=> 🚀 인증관련 로직 생성

.github/workflows/prod-deploy.yml, Dockerfile, src/main/java/com/campper/domain/like/camps/CampDibsController.java, src/main/java/com/campper/domain/like/camps/service/CampDibsService.java, src/main/java/com/campper/domain/like/camps/service/CampDibsServiceImpl.java, src/main/java/com/campper/global/config/SwaggerConfig.java
---
좋아요 중복 확인용 api 생성
---
refac/dib
---
이슈 번호
- close #43
---
특이사항
=> :hammer: refac(dib): 좋아요 중복 확인용 api 생성 #43

src/main/java/com/campper/domain/votes/VoteController.java, src/main/java/com/campper/domain/votes/dto/request/PutVoteDto.java, src/main/java/com/campper/domain/votes/repository/VoteRepository.java, src/main/java/com/campper/domain/votes/service/VoteService.java, src/main/java/com/campper/domain/votes/service/VoteServiceImpl.java, src/main/resources/mapper/vote.xml
---
투표 여부 확인 API 추가
투표 수정 API 추가
기타 에러사항 수정
---
refac/vote
---
이슈 번호
-open #41 
---
특이사항
=> 🚀 / 🔨  투표 리팩토링 및 기능 추가

src/main/java/com/campper/domain/votes/VoteController.java, src/main/java/com/campper/domain/votes/entity/Vote.java, src/main/java/com/campper/domain/votes/service/VoteService.java, src/main/java/com/campper/domain/votes/service/VoteServiceImpl.java, src/main/resources/mapper/voteCamp.xml
---
투표 수정 기능 오류 수정
---
refac/vote
---
이슈 번호
- open #41 
---
투표 및 캠핑 평점 DB 초기화
=> :lady_beetle: bug(vote): 투표 수정 기능 오류 수정 #41
